package com.virexalo.editor.model

enum class EditorTool {
    NONE, TRIM, SPLIT, TEXT, OVERLAY, DRAW, AUDIO, VOICE_OVER, SUBTITLES,
    CROP, CANVAS, SPEED, FILTERS, EFFECTS, TRANSITIONS, MASK, CHROMA_KEY,
    KEYFRAMES, ADJUST, REVERSE
}
